### ISSUE TITLE
Tried to start task xxx while in foreground  

### ISSUE THREAD

**Issue by cbjs** [vikeri/react-native-background-job#17]
can't to figure out how to fix this.

**Comment by vikeri** [comment]
Are you using the latest version: 1.1.2?

**Comment by cbjs** [comment]
@vikeri 

yes.

"react": "16.0.0-alpha.6",
"react-native": "0.43.2",
"react-native-background-job": "^1.1.2",

--
error shows up when reloading in debug mode.
but seems to be no problem in release mode.

**Comment by vikeri** [comment]
Ok weird, can you share the code?

**Comment by cbjs** [comment]
@vikeri 

background.js
`
import BackgroundJob from 'react-native-background-job';

const JOB_MESSAGE_CHECK = "message";

// register background task
export const register = () => {
  BackgroundJob.register({
    jobKey: JOB_MESSAGE_CHECK,
    job: () => {
      console.log('check message');
    }
  })
}

export const schedule = () => {
  BackgroundJob.getAll({
    callback: (jobs) => {
      let allJobKeys = new Set(jobs.map(job => job.jobKey));
      if (!allJobKeys.has(JOB_MESSAGE_CHECK)) {
        BackgroundJob.schedule({
          jobKey: JOB_MESSAGE_CHECK,
          timeout: 5000
        });
      }
    }
  });

}

`

index.js
`
import React, { Component } from 'react';
import { View } from 'react-native';
import { register as registerJobs, schedule as scheduleJobs } from './background';

class RootWrapper extends Component {
  render() {
    return <View/>
  }
}

registerJobs();
scheduleJobs();

export default RootWrapper;
`

**Comment by cbjs** [comment]
@vikeri 

I try to add isAppInForeground() check in method BackgroundJob#onStartJob().

it seems work.

![image](https://cloud.githubusercontent.com/assets/1215843/24987048/4839958c-2030-11e7-9209-e22f63f73797.png)

**Comment by vikeri** [comment]
Interesting, I have never seen this but I guess it could be related to different Android versions/maker. What device and Android version are you running? 

That fix looks reasonable btw, you're using `isAppInForeground()` from `HeadlessService.java` but you made it public? If you submit a PR I'll try to merge it asap. Since I couldn't reproduce the issue I'd appreciate a PR since I wouldn't be able to verify the issue myself.

**Comment by vikeri** [comment]
Added js styling to your previous comment btw #ocd

**Comment by vikeri** [comment]
@cbjs Could you try the latest version `1.2.0`? I added a couple of additional checks that hopefully addresses this.

**Comment by ferdicus** [comment]
Hey @vikeri, having the same issue here with `1.2.0`:

Device: `Moto G 2014 LTE - 6.0.1`


```json
"react": "16.0.0-alpha.6",
"react-native": "0.43.4",
"react-native-background-job": "^1.2.0"
```

My Code:
```js
BackgroundJob.register({
  jobKey: "backgroundJob",
  job: () => {
    console.log('hello')
  }
});

BackgroundJob.schedule({
  jobKey: "backgroundJob",
  period: 5000,
  timeout: 5000
});
```
So basically the simplest of examples.

No issues when app goes from active to background and back to active again.
Error shows up when app is closed and reopened.

Please let me know if you need more information and thanks for writing `react-native-background-job` 👍

**Comment by cbjs** [comment]
@vikeri I tried, still not working.

**Comment by cbjs** [comment]
@vikeri to fix this issue, I have to use allowedInForeground option
check this pull request.
https://github.com/vikeri/react-native-background-job/pull/21

**Comment by vikeri** [comment]
And if you could dump your logs here it would be great:
```
adb logcat -d | grep "backgroundjob\|ReactNativeJS" > logcat.txt
```

**Comment by bevkoski** [comment]
I was also able to reproduce this using the provided example project (https://github.com/vikeri/react-native-background-job/tree/master/example) and the latest version of the library (**1.2.0**).

This is the error that I get:

![error-small](https://cloud.githubusercontent.com/assets/6344196/25696610/1cbf6dee-30b8-11e7-8f55-7417653f4386.png)

## How To Reproduce It

1. Schedule a job
2. Press the back button so that the app goes into background
3. Hold the main hardware button to list all active apps
4. Open the app once again by selecting it from the list
5. Hold the main hardware button to list all active apps once again
6. Kill the app by swiping it to the side
7. Reopen the app from the list of installed apps
8. The crash occurs

Sometimes, it does not occur the first time. Repeat steps 2 to 7 if it does not.

## Log Dump

```
D/backgroundjob(16178): Initializing BackgroundJob		
D/backgroundjob(16178): Getting constants		
D/backgroundjob(16178): Getting all jobs		
I/ReactNativeJS(16178): Running application "backtest" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF		
D/backgroundjob(16178): Getting all jobs		
I/ReactNativeJS(16178): 'Jobs:', []		
V/backgroundjob(16178): Scheduling: Hej, timeout: 5000, period: 5000, network type: 2, requiresCharging: false, requiresDeviceIdle: false, alwaysRunning: false, notificationTitle: null, notificationText null, notificationIcon: null		
D/backgroundjob(16178): Getting all jobs		
D/backgroundjob(16178): Fetching job 72429		
I/ReactNativeJS(16178): 'Jobs:', [ { requiresDeviceIdle: false,		
I/ReactNativeJS(16178):     networkType: 2,		
I/ReactNativeJS(16178):     notificationTitle: null,		
I/ReactNativeJS(16178):     timeout: 5000,		
I/ReactNativeJS(16178):     jobKey: 'Hej',		
I/ReactNativeJS(16178):     notificationText: null,		
I/ReactNativeJS(16178):     period: 5000,		
I/ReactNativeJS(16178):     persist: true,		
I/ReactNativeJS(16178):     alwaysRunning: false,		
I/ReactNativeJS(16178):     notificationIcon: null,		
I/ReactNativeJS(16178):     requiresCharging: false } ]		
D/backgroundjob(16178): Sceduling job 72429		
D/backgroundjob(16178): Job (72429) scheduled successfully!		
I/ReactNativeJS(16178): Background Job fired!		
W/ActivityManager(  782): Scheduling restart of crashed service com.backtest/com.pilloxa.backgroundjob.HeadlessService in 1000ms		
I/ActivityManager(  782): Start proc com.backtest for service com.backtest/com.pilloxa.backgroundjob.HeadlessService: pid=16375 uid=10413 gids={50413, 9997, 3003, 1028, 1015} abi=armeabi-v7a		
D/backgroundjob(16375): Initializing BackgroundJob		
D/backgroundjob(16375): Getting constants		
D/backgroundjob(16375): Getting all jobs		
D/backgroundjob(16375): Fetching job 72429		
I/ReactNativeJS(16375): Background Job fired!		
I/ReactNativeJS(16375): Running application "backtest" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF		
D/backgroundjob(16375): Getting all jobs		
D/backgroundjob(16375): Fetching job 72429		
I/ReactNativeJS(16375): 'Jobs:', [ { requiresDeviceIdle: false,		
I/ReactNativeJS(16375):     networkType: 2,		
I/ReactNativeJS(16375):     notificationTitle: null,		
I/ReactNativeJS(16375):     timeout: 5000,		
I/ReactNativeJS(16375):     jobKey: 'Hej',		
I/ReactNativeJS(16375):     notificationText: null,		
I/ReactNativeJS(16375):     period: 5000,		
I/ReactNativeJS(16375):     persist: true,		
I/ReactNativeJS(16375):     alwaysRunning: false,		
I/ReactNativeJS(16375):     notificationIcon: null,		
I/ReactNativeJS(16375):     requiresCharging: false } ]		
D/backgroundjob(16375): Sceduling job 72429		
D/backgroundjob(16375): Job (72429) scheduled successfully!		
W/ActivityManager(  782): Scheduling restart of crashed service com.backtest/com.pilloxa.backgroundjob.HeadlessService in 26268ms		
D/backgroundjob(16579): Initializing BackgroundJob		
D/backgroundjob(16579): Getting constants		
D/backgroundjob(16579): Getting all jobs		
I/ReactNativeJS(16579): Running application "backtest" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF		
D/backgroundjob(16579): Getting all jobs		
I/ReactNativeJS(16579): 'Jobs:', []
```

## Device Info
Samsung SM-N9005
Android 5.0, API 21

**Comment by ferdicus** [comment]
Hey @vikeri, a small addition - you might want to check this with Remote JS Debugging enabled.
Seems to me, that is increasing the likeliness of this issue appearing.

**Comment by bevkoski** [comment]
@ferdicus, just as a note, the error shown above was reproduced with Remote JS Debugging **disabled**.

**Comment by ferdicus** [comment]
@bevkoski, sorry I didn't mean it is ONLY showing when RJSD is enabled - I just had the experience, that it happened more often.

**Comment by vikeri** [comment]
@bevkoski Thanks a lot! This will make debugging a lot easier! I'm pretty swamped at the moment but I'll try to fix it during the weekend.

**Comment by vikeri** [comment]
Just released `1.2.2` and at least I wasn't able to reproduce it again using @bevkoski's steps. Please try that version and see if this issue persists.

**Comment by bevkoski** [comment]
@vikeri, unfortunately, the issue still occurs with the **1.2.2** release. I had a hard time reproducing  it with the steps listed above, but I finally managed to reproduce it by following different steps. Again, I used the example app that you have provided.

1. Install the app with `react-native run-android`
2. Schedule a job
3. Press the hardware back button so that the app goes into background
4. Execute `adb logcat | grep Background` in the terminal
5. Wait for one execution of the background job (you should see the message "**Background Job fired!**" in the terminal)
6. Hold the main hardware button to list all active apps
7. Kill the app by swiping it to the side
8. Reopen the app from the list of installed apps
9. The error occurs

**Comment by vikeri** [comment]
@bevkoski I can't reproduce this by following the steps you outlined. Are you testing in an emulator or on a real device?

**Comment by vikeri** [comment]
@bevkoski Found that I reused a function and redid the fix there, so try `1.2.3` which I just published. Sort of stabbing in the dark here but since I can't reproduce the issue myself it's kinda hard.

**Comment by bevkoski** [comment]
@vikeri, yes I am using a real device - **Samsung SM-N9005, Android 5.0, API 21**. I'll try to check if the same thing occurs with newer devices.

I just tried **1.2.3** and I can confirm that the issue persists.

The use case is very specific. When following the steps I described yesterday (https://github.com/vikeri/react-native-background-job/issues/17#issuecomment-299839232) you must allow exactly one execution of the background job, immediately kill the app and then immediately open it. I get the same crash (https://github.com/vikeri/react-native-background-job/issues/17#issuecomment-299132420) and the log dump looks pretty similar.

A very important point here, which might help in identifying the issue, is that the crash occurs only with jobs for which the `alwaysRunning` flag is set to `false` (the default option). If I set the `alwaysRunning` flag to `true` and activate a ForegroundService instead of using JobScheduler for the job, it works smoothly. The example app uses the default option (`false`) - https://github.com/vikeri/react-native-background-job/blob/master/example/index.android.js#L58, which is why it is also reproducible with it.

**Comment by vikeri** [comment]
@bevkoski Ok interesting! I'll continue some testing. I did everything as you had it specified except for allowing exactly one execution.

**Comment by muneebsajjad** [comment]
i am having the same issue what is the workaround until fix ?

**Comment by cbjs** [comment]
check this pull request: https://github.com/vikeri/react-native-background-job/pull/21
I use this as a temporary workaround

**Comment by muneebsajjad** [comment]
**Just to give more insight about the bug**

    1- Install the app with react-native run-android or react-native run-android --variant=Release 
    2- Schedule a job
    3- Minimize the app by pressing menu button
    4- Let the app minimize for few minutes lets say 5 or 7 mints
    5- Hold the main hardware button to list all active apps
    6- Kill the app by swiping it to the side
    7- Reopen the app from the list of installed apps
    8- The crash occures 

>  NOTE :- For me crash occure exactly two time on third attempt to launch the app. it works fine
    i want to deploy my app on app store but just waiting for this fix.

**React version** 
  "react": "^16.0.0-alpha.6",
  "react-native": "^0.44.2",
**Background Job version =**
  "react-native-background-job": "^1.2.3",

**Comment by muneebsajjad** [comment]
@cbjs  how do you recompile the source after adding  this check ?

> if(isAppInForeground())
 >return false;

**Comment by dbrenden** [comment]
I just wanted to add a quick thing. I will get this 'Tried to start task ...' error in similar circumstances even if I cancel the job. 
I would start the app
1. start the job
2. let it fire once
3. cancel the job
4. kill the app by swiping on the active apps list 
5. start the app again
6. crash
I would try to force the job via adb to see if the job had actually cancelled, and it did. My app had no jobs scheduled at all, but for some reason it was still  I'm curious if this has happened @muneebsajjad or @bevkoski. I would share some of my code, but I'm writing it in clojurescript, so it may not be all that helpful. I do however have logs. 

`05-30 22:14:19.447 18248 18267 D backgroundjob: Initializing BackgroundJob                                                                                                 [32/4351]
05-30 22:14:20.636 18248 18266 D backgroundjob: Getting constants
05-30 22:14:20.637 18248 18266 D backgroundjob: Getting all jobs
05-30 22:14:20.637 18248 18266 D backgroundjob: Fetching job -927199289
05-30 22:14:20.782 18248 18266 I ReactNativeJS: Registering function
05-30 22:14:20.851 18248 18266 I ReactNativeJS: Job Fired, comparing current time with recording-date
05-30 22:14:20.852 18248 18266 I ReactNativeJS: NOW: 1496193260850 Recording-date:
05-30 22:14:20.852 18248 18266 I ReactNativeJS: After recording date: true
05-30 22:14:20.853 18248 18266 I ReactNativeJS: STARTING RECORDING
05-30 22:14:20.862 18248 18266 I ReactNativeJS: RECORDING FOR: 20000 msecs
05-30 22:14:20.867 18248 18266 I ReactNativeJS: 'SUM OF SLEEPS: ', 1800000, ' PERIOD: ', 1800000, ' (should be equal)'
05-30 22:14:31.742 18248 18266 I ReactNativeJS: Running application "FourThirtyThree" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === false, development-level warning
are OFF, performance optimizations are ON
05-30 22:14:40.877 18248 18266 I ReactNativeJS: STOPPING RECORDING
05-30 22:14:44.228 18248 18267 D backgroundjob: Cancelling job: fourThirtyThreeRecord (-927199289)
05-30 22:14:54.339 18347 18347 E AndroidRuntime: FATAL EXCEPTION: main
05-30 22:14:54.339 18347 18347 E AndroidRuntime: Process: com.fourthirtythree, PID: 18347
05-30 22:14:54.339 18347 18347 E AndroidRuntime: java.lang.IllegalStateException: Tried to start task fourThirtyThreeRecord while in foreground, but this is not allowed.
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at com.facebook.react.jstasks.HeadlessJsTaskContext.startTask(HeadlessJsTaskContext.java:92)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at com.facebook.react.HeadlessJsTaskService.invokeStartTask(HeadlessJsTaskService.java:122)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at com.facebook.react.HeadlessJsTaskService.access$000(HeadlessJsTaskService.java:44)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at com.facebook.react.HeadlessJsTaskService$1.onReactContextInitialized(HeadlessJsTaskService.java:107)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.setupReactContext(ReactInstanceManager.java:867)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager.access$700(ReactInstanceManager.java:108)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManager.java:237)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at com.facebook.react.ReactInstanceManager$ReactContextInitAsyncTask.onPostExecute(ReactInstanceManager.java:203)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at android.os.AsyncTask.finish(AsyncTask.java:667)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at android.os.AsyncTask.-wrap1(AsyncTask.java)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6121)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-30 22:14:54.339 18347 18347 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)`

**Comment by vikeri** [comment]
I think I have a fix running, please try the beta version: "react-native-background-job@1.2.4-0"

**Comment by 0is1** [comment]
@vikeri "react-native-background-job@1.2.4-0" seems to work for me! Thank you! :)

**Comment by holyxiaoxin** [comment]
look up `npm show react-native-background-job versions` to look for pre-released versions.

Tried it again with 1.2.4-0, you need to set period to 900000, or let it default to 90000, running on Android 7.0. The first triggered event was immediate when I killed the app, the next event triggered was 18 mins later.

Thanks for the library! @vikeri  (:

**Comment by vikeri** [comment]
Closed by #36

**Comment by maheshsgr** [comment]
How you guys are checking if  appIsInForeground and will service rerun if it return true or special handling need to be done. Id timeout key mendatory
